import { atom } from 'recoil';
import { persistAtom } from './persist';

export const planresult = atom({
  key: 'planresult',
  default: {
    result: [
      {
        small_goal: '',
        mini1: '',
        mini2: '',
        mini3: '',
        mini4: '',
        cmini1: 0,
        cmini2: 0,
        cmini3: 0,
        cmini4: 0,
        total: 0,
        date: '',
      },
      {
        small_goal: '',
        mini1: '',
        mini2: '',
        mini3: '',
        mini4: '',
        cmini1: 0,
        cmini2: 0,
        cmini3: 0,
        cmini4: 0,
        total: 0,
        date: '',
      },
      {
        small_goal: '',
        mini1: '',
        mini2: '',
        mini3: '',
        mini4: '',
        cmini1: 0,
        cmini2: 0,
        cmini3: 0,
        cmini4: 0,
        total: 0,
        date: '',
      },
      {
        small_goal: '',
        mini1: '',
        mini2: '',
        mini3: '',
        mini4: '',
        cmini1: 0,
        cmini2: 0,
        cmini3: 0,
        cmini4: 0,
        total: 0,
        date: '',
      },
    ],
    score: 0,
  },
  effects_UNSTABLE: [persistAtom],
});
