name: storybook

on:
  push:
    branches: ['main', 'deploy']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
      
    steps:
      - name:  Use repository source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./
          
      - name: Build storybook
        run: |
          npm run build-storybook
          mv ./storybook-static ./build/storybook
        working-directory: ./

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
