name: Deploy Stroybook to GithubPages

on:
  push:
    branches: ['main', 'deploy']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
      
    steps:
      - name:  Use repository source
        uses: actions/checkout@v3
        
      - name: Use node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

      - name: Install dependencies
        run: |
          npm install
          
      - name: Build storybook
        run: |
          npm run build-storybook
          mv ./storybook-static ./build/storybook
        working-directory: ../

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../build
