name: Deploy Stroybook to GithubPages

on:
  push:
    branches: ['main', 'deploy']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
      
    steps:
      - name: Build storybook
        run: |
          npm install
          npm run build-storybook
        working-directory: ../

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../storybook-static
